version: '3.5'

services:
  redis:
    image: redis:6.0.6-alpine
  backend:
    image: backend-example
    ports:
      - 8000:8000
    volumes:
      - ./logs.txt:/usr/app/logs.txt
    environment: 
      - FRONT_URL=http://localhost:5000
      - REDIS=redis
  frontend:
    image: frontend-example
    ports: 
      - 5000:5000
    environment: 
      - API_URL=http://localhost:8000