version: '3.5'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
  redis:
    image: redis:6.0.6-alpine
  backend:
    image: backend-example
    ports:
      - 8000:8000
    volumes:
      - ./logs.txt:/usr/app/logs.txt
    environment: 
      - FRONT_URL=http://localhost:5000
      - REDIS=redis
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
    depends_on:
      - db
  frontend:
    image: frontend-example
    ports: 
      - 5000:5000
    environment: 
      - API_URL=http://localhost:8000